/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub fn create_ahrs() -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn free_ahrs(ahrs: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn update_no_magnetometer(
        ahrs: *mut ::std::os::raw::c_void,
        delta_time: f64,
        gyro_x: f64,
        gyro_y: f64,
        gyro_z: f64,
        accel_x: f64,
        accel_y: f64,
        accel_z: f64,
    );
}
extern "C" {
    pub fn get_quaternion(
        ahrs: *mut ::std::os::raw::c_void,
        w: *mut f64,
        x: *mut f64,
        y: *mut f64,
        z: *mut f64,
    );
}
extern "C" {
    pub fn get_linear_acceleration(
        ahrs: *mut ::std::os::raw::c_void,
        x: *mut f64,
        y: *mut f64,
        z: *mut f64,
    );
}
